---
title: "MA679 Final Project: Model"
author: "Team 9"
date: "05/04/2021"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(plyr)
library(reshape2)
library(tidyr)
library(viridis)
library(psych)
library(rstanarm)
library(arm)
library(randomForest)
knitr::opts_chunk$set(echo = TRUE)
```


```{r }
oral <-  read.csv("oral_cancer_data.csv")

break1 <-  c(21840, 57160, 79640, 106760)
label <-  c("Low","Mid","High")
oral$Income_Level <-  oral$Median.Household.Income
oral$Income_Level <- cut(oral$Income_Level, break1, label,include.lowest = T)
```


```{r }
oral$Sex <-  ifelse(oral$Sex == "Male", 1, 0)
oral$Race <-  factor(oral$Race, levels = c("White", "Asian or Pacific Islander", "Black", "Hispanic","American Indian/Alaska Native"))
oral$Insurance <- ifelse(oral$Insurance == "Uninsured",0,1)
```

# Feature Selection
```{r}
# Train-Test Split
set.seed(1)
split_index <-  sort(sample(nrow(oral), nrow(oral)*0.8))
trainset <-  oral[split_index,]
testset <-  oral[-split_index,]
```


```{r}
# Randomm Forest-based selection
set.seed(1)
rf_select <-  randomForest(as.factor(Match) ~ Bachelors.Education + Sex + Race+ Insurance + Below.Poverty + Unemployed + Language.Isolation + Income_Level + Sex:Race + Cause.of.Death + SEER.Registry + X9th.Education + HS.Education + Age.at.Diagnosis + Cancer_Stage, data = trainset, mtry = 4, importance = T)

# Visualize the importance
# importance(rf_select)
varImpPlot(rf_select)
```


# Model

## Logistic Regression

```{r}
m1 <-  glm(Match ~ Cancer_Stage  + Language.Isolation + X9th.Education + Bachelors.Education + Unemployed + Age.at.Diagnosis + Below.Poverty + Race + Sex + Race:Sex + Insurance, data = trainset, family = binomial(link = "logit"))

summary(m1)
```


```{r }
# Residual Plor-Logistic Model
binnedplot(fitted(m1), residuals(m1))
```


```{r}
logis_test_pred <- factor(ifelse(predict(m4, newdata = testset,type = "response") < 0.5, 0, 1))

table(logis_test_pred,testset$Match)
```


```{r }
(690+430)/(690+141+136+430)
```
